### ISSUE TITLE
Error while running basic compojure-api

### ISSUE THREAD

**Issue by srinidagda** [metosin/compojure-api-examples#6]
I have created one project ``lein new compojure-api my-app`` command and ran the project with ``lein run`` command
I am getting this error.
``Exception in thread "main" java.lang.AbstractMethodError: Method compojure/api/routes/Route.invoke()Ljava/lang/Object; is abstract, compiling:(/private/var/folders/sc/_5vqrzqd6957db1699lb0lm00000gq/T/form-init5955368636245682796.clj:1:125)``

**Comment by miikka** [comment]
Hi! A new project created with `lein new compojure-api my-app` does not do anything with `lein run`, because there's no `:main` configured in project.clj. Have you configured `lein run` to do something, or did you mean `lein ring server`?

**Comment by srinidagda** [comment]
Hi Miikka, I resolved the issue and uploaded to my github account you can look into the project.
https://github.com/srinidagda/clojure-api-example.git

**Comment by miikka** [comment]
Okay, so it works now? That's good. I'll close this issue, then.

By the way, if you need help in the future, it's often quicker to ask on the [#ring-swagger](https://clojurians.slack.com/messages/ring-swagger/) channel on the Clojurians Slack chat than by opening an issue here. You can create account [here](http://clojurians.net/).

**Comment by srinidagda** [comment]
@miikka Yes you can close the issue. Thanks for quick help.
